import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_KR} from 'next/font/google'

import Head from 'next/head'

const inter = Noto_Sans_KR({
  weight: ['500'],
  subsets: ['latin'],
 })

export const metadata: Metadata = {
  title: 'c App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
       <title>Next.js22</title>
    </Head>
      <body className={inter.className}>
        {children}</body>
    </html>
  )
}
